# Generated by Django 5.1.4 on 2025-10-30 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='The number must be of 10-15 digits, with optional + at start!', regex='^\\+?\\d{10-15}$')]),
        ),
    ]
