# Generated by Django 5.2.7 on 2025-11-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
    ]
