# Generated by Django 5.2.7 on 2025-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='drive_link',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
